######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 4 16:05:33 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myqtled.h
FORMS += testled.ui
SOURCES += main.cpp myqtled.cpp
