######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 28 14:30:14 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qtled.h
FORMS += testx11.ui
SOURCES += main.cpp qled.cpp
